# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: icu-mortality-prediction
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  memorySize: 10240
  timeout: 30
  lambdaHashingVersion: 20201221
  region: ap-southeast-2

functions:
  predict:
    image: 
      uri: 375955733054.dkr.ecr.ap-southeast-2.amazonaws.com/icu-mortality-prediction:latest
      command:
        - handler.predict
    events:
      - httpApi:
          path: /predict
          method: post
          cors: true

